import * as Yup from "yup";
export const receiptRegisterDetailsSchema = Yup.object().shape({
receipt_no: Yup.string().required("Receipt No is required"),
ulb_id: Yup.number().required("Ulb  is required"),
primary_acc_code_id: Yup.number().required("Primary Acc Code  is required"),
revenue_module_id: Yup.number().required("Revenue Module  is required"),
paid_by: Yup.string().required("Paid By is required"),
receipt_mode_id: Yup.number().required("Receipt Mode  is required"),
receipt_date: Yup.string().required("Receipt Date is required"),
cheque_or_draft_no: Yup.string().required("Cheque Or Draft No is required"),
bank_id: Yup.number().required("Bank  is required"),
cash_amount: Yup.number().required("Cash Amount is required"),
bank_acc_no: Yup.string().required("Bank Acc No is required"),
deposit_date: Yup.string().required("Deposit Date is required"),
realisation_date: Yup.string().required("Realisation Date is required"),
wheather_reaturned: Yup.string().required("Wheather Reaturned is required"),
remarks: Yup.string().required("Remarks is required"),
entered_by: Yup.string().required("Entered By is required"),
designation: Yup.string().required("Designation is required"),
print_name: Yup.string().required("Print Name is required"),
checked_by: Yup.string().required("Checked By is required"),
designation1: Yup.string().required("Designation1 is required"),
print_name1: Yup.string().required("Print Name1 is required"),
})
